### ISSUE TITLE
Organize controllers and routes for ideas, issues...

### ISSUE THREAD

**Issue by andrerpena** [matterspace/matterspace#1]
Today, `http://localhost:4000/p/matterspace/Ideas` is hitting the `Products` controller, but it should actually hit the `IdeasController` controller in the `Index` action.

The same is valid for issues, backlog and everything. The structure of the Controllers and Views should be refactored.

The routes should also be refactored, so `http://localhost:4000/p/matterspace/Ideas` won't hit the `Products` controller anymore

**Comment by andrerpena** [comment]
@AdowTatep , you should start with this one

**Comment by AdowTatep** [comment]
@andrerpena should I follow the pattern for naming controllers in plural for everything or should we make exceptions in cases like "backlog" or "QA" ?

**Comment by andrerpena** [comment]
Make exceptions =)

Em 15 de jan de 2017 6:56 PM, "Matheus Assis" <notifications@github.com>
escreveu:

**Comment by AdowTatep** [comment]
Finished development

**Comment by andrerpena** [comment]
Good job!
