### ISSUE TITLE
Create the "New [thread]" form - Version 1

### ISSUE THREAD

**Issue by andrerpena** [matterspace/matterspace#2]
@AdowTatep 

The most important part of the "New [thread]" form is the Markdown editor, but, even though the component is 100% ready, I didn't fully integrate it into MS yet.

So, here are the instructions:

Create a dummy form not caring too much about styles. I'll always be very careful and rigorous with styling. You can try to do your best, if you want, but I'll always adjust it to look as good as possible. I don't expect you to create perfect looking forms because that's my responsibility. But I won't care if you try to.

The point here is: **While I don't fully integrate React-Mde within MS, you can just work with a title textbox and a markdown textarea**. I will replace your markdown text area with the real deal in the near future.

Please, create the "New [thread]" in such a way that it's implemented only once for all types of threads. The product layout should be utilized. So, everything from THE MENU UP should remain the same 

![image](https://i.imgur.com/MebLPv8.png)

The actual form should START BENEATH the main menu, **keeping context** (I have to know I'm inside Issues, for instance)

Example:

![image](https://i.imgur.com/2guP0pU.png)

This forms should be triggered in URLs like this:

`http://localhost:4000/p/matterspace/Ideas/new` and `http://localhost:4000/p/matterspace/Ideas/{id}/edit`

**Comment by andrerpena** [comment]
@AdowTatep Before you finish this up I should be able to fully integrate the Markdown editor

**Comment by AdowTatep** [comment]
Finished development

**Comment by andrerpena** [comment]
Yeaah!!! I'm going to check this out this afternoon

**Comment by andrerpena** [comment]
@AdowTatep . I think we should probably close this issue when some minor issues are solved:

- The form should actually save an idea, for instance, when the ideia is submitted.
- Let's change the "submit" button text to reflect what's happening. Example: "Submit new idea"
- Let's prevent the user from submitting when either the tittle or the text has no text. We can just disable the submit button using jQuery.

**Comment by AdowTatep** [comment]
Great! I'll work on it

**Comment by AdowTatep** [comment]
Minor issues solved, closing issue.
