### ISSUE TITLE
Can we make the settings button a menu button just like in GitHub?

### ISSUE THREAD

**Issue by andrerpena** [matterspace/matterspace#25]
![image](https://cloud.githubusercontent.com/assets/1581429/22669377/68bf697a-ecab-11e6-8a0e-8f06551b2e1b.png)

@AdowTatep , you've put the settings button as a floating button. I feel it's kind of out of place.. Do you agree on moving it to the the menu just like GH does?

![image](https://cloud.githubusercontent.com/assets/1581429/22669434/9e5f1918-ecab-11e6-91c6-49957fc9ceb4.png)

**Comment by andrerpena** [comment]
It got better IMHO, but you didn't preserve the layout. I mean.. When you click the settings, you should stil be able to see the Get it button and all 😄

**Comment by AdowTatep** [comment]
Oh, sorry. I'll fix that in the next commit!
